name: Andoid CI

on:
  push:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Build with Gradle
        run: ./gradlew build

      - name: Run unit tests
        run: ./gradlew testDebugUnitTest jacocoTestReport

      - name: Publish test reports as artifacts
        uses: actions/upload-artifact@v2
        with:
          name: test-reports
          path: app/build/reports

      - name: Build APK
        run: ./gradlew assembleDebug

      - name: Publish APK as artifact
        uses: actions/upload-artifact@v2
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/app-debug.apk